name: My First Pipeline
on: 
  push:
    branches:
      - test
jobs:
  run-linux-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Display Success Message
        run: echo "Git hub got a push event and the pipeline is successful"
      - name: Run linux commands
        run: |
          echo "Running Linux commands..."
          date
          pwd
          ls -la
      

